--- #YAML:1.0
name:               Template-Toolkit
version:            2.22
abstract:           comprehensive template processing system
author:
    - Andy Wardley <abw@wardley.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    AppConfig:     1.56
    File::Spec:    0.8
    File::Temp:    0.12
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
